package com.dicoding.mycomposeapp.model

import com.dicoding.mycomposeapp.R

object FakeMemberDataSource {
    val dummyMembers = listOf(
        Member(1, "Taeil", "June 14, 1994", "Moon Tae-il (Hangul: 문태일), better known by the mononym Taeil is a South Korean singer. He is the lead vocalist of the South Korean music group NCT. He is also a member of the sub-units NCT U and NCT 127 under the company SM Entertainment. Taeil debuted on April 10, 2016 in the NCT U rotation unit and NCT 127 on July 7, 2016. He is also one of the NCT members who was initially introduced through SM Rookies in 2015.", "Main Vocalist", R.drawable.member_1),
        Member(2, "Johnny", "February 9, 1995", "Seo Young-ho (서영호) or Johnny (쟈니) or better known as Johnny Suh is a Korean-American singer, model and rapper under contract to SM Entertainment. He is a member of the male vocal group NCT and the sub-unit NCT 127. Johnny was confirmed to be part of NCT 127 on December 27, 2016. In September 2008, Johnny passed the SM Global Audition in Chicago and became a trainee at SM Entertainment.", "Lead Dancer, Sub Rapper, Sub Vocalist", R.drawable.member_2),
        Member(3, "Taeyong", "July 1, 1995", "Lee Tae-yong (Hangul: 이태용), known by his mononym Taeyong, is a South Korean lead rapper, songwriter, lead dancer, choreographer, visual, and singer. He is the leader and member of the South Korean male vocal group NCT in the subunit NCT U and is the leader of NCT 127. He is also currently a member of another SM Entertainment vocal group, SuperM.", "Leader, Main Rapper, Main Dancer, Sub Vocalist, Visual, Center, Face of the Group", R.drawable.member_3),
        Member(4, "Yuta", "October 26, 1995", "Yuta Nakamoto (中本 悠太) professionally known as Yuta (유타) is a Japanese singer, dancer, rapper, and actor based in South Korea. He is a member of the South Korean male vocal group, NCT, he auditioned for the SM Global Audition in Japan in 2012 he passed the audition then joined SM Rookies in 2013, shortly after joining he debuted in the second sub-unit of NCT, NCT 127 in 2016. Making him the first idol in SM Entertainment to come from Japan.", "Lead Dancer, Sub Vocalist, Sub Rapper", R.drawable.member_4),
        Member(5, "Doyoung", "February 1, 1996", "Kim Dong-young (김동영), also known as Doyoung, is a South Korean singer, actor and host. He is best known as a member of the South Korean male vocal group NCT and its two sub-units NCT U and NCT 127. Doyoung debuted in April 2016 as a non-permanent member of NCT U and a member of the Seoul-based permanent subunit, NCT 127, in January 2017. In 2021, he starred in the television drama Midnight Cafe Season 3 -The Curious Stalker and appeared in the musical Marie Antoinette.", "Main Vocalist", R.drawable.member_5),
        Member(6, "Jaehyun", "February 14, 1997", "Jeong Yun-o (Hangul: 정윤오; born Jeong Jae-hyun (Hangul: 정재현), better known by the stage name Jaehyun, is a South Korean singer, songwriter, and actor. He is best known as a member of the South Korean male vocal group NCT and its sub-units, NCT U and NCT 127. Jaehyun debuted in April 2016 as a member of the rotational unit NCT U and became a permanent member of the unit NCT 127 in July 2016. He is also a former host of Inkigayo from October 2019 to February 2021.", "Main Vocalist, Lead Dancer, Sub Rapper, Visual", R.drawable.member_6),
        Member(7, "Winwin", "October 28, 1997", "Dǒng Sīchéng (董思成) or Winwin (윈윈) is a Chinese singer under contract to SM Entertainment. He is a member of the male vocal group NCT and its sub-units NCT 127, NCT U and WayV. He is also a vocalist, rapper, and visual. WinWin was first introduced as part of the NCT 127 sub-unit in 2016 alongside Taeil, Taeyong, Yuta, Jaehyun, Mark, and Haechan.", "Lead Dancer, Sub Vocalist", R.drawable.member_7),
        Member(8, "Jungwoo", "February 19, 1998", "Kim Jungwoo (김정우) is a South Korean singer under contract to SM Entertainment. He is a member of the male vocal group NCT and the sub-units NCT U and NCT 127. He made it to SM Entertainment after passing the weekly auditions. Jungwoo was introduced as part of SM Rookies on April 18, 2017. On January 30, 2018, SM Entertainment announced that Jungwoo would debut as a member of NCT", "Lead Vocalist, Lead Dancer", R.drawable.member_8),
        Member(9, "Mark", "August 2, 1999", "Mark Lee, better known as Mark is a Canadian rapper, dancer, and singer. He is a member of the South Korean boy band, NCT. Mark is a member of 3 NCT sub-units, namely NCT U, NCT 127, and NCT Dream. He is also currently a member of the super group SuperM. Mark also often contributes as a soloist and collaborates with other musicians.", "Main Rapper, Main Dancer, Sub Vocalist", R.drawable.member_9),
        Member(10, "Haechan", "June 6, 2000", "Lee Dong-hyuck better known as Haechan, is a South Korean singer. He is a member of the South Korean boy band, NCT, as well as its three sub-units, NCT 127, NCT Dream, and NCT U. Besides making music through the NCT Music Group, NCT U, NCT Dream and NCT 127, Haechan also contributes as a soloist and collaborates with other musicians.", "Main Vocalist, Lead Dancer, Maknae", R.drawable.member_10)
    )
}